#get_volleyball_player
#get_team
#get_height
#get_year
#get_nationality #sofijackson

NATIONALITY = {'ALB':'SALA CHIARA',
               'ARG':'BECHIS MARTA',
               'AUT':'ANGELINA GIULIA',
               'BEL':['JASPER MARRIT','PERICATI YLENIA','CVETNIC LEA','PARLANGELI FRANCESCA','BRIDI ULRIKE','BIGANZOLI FEDERICA'],
               'BIH':'BOTEZAT ALEXANDRA',
               'BLR':'BERTI BEATRICE',
               'BRA':['VEGLIA TIZIANA','DECORTES CLARA'],
               'BUL':'NICOLETTI ANNA',
               'CAN':'CASILLO LUISA',
               'CRO':['CARCACES KENIA', 'AGRIFOGLIO BEATRICE', 'SCARABOTTINI ANASTASIA', 'CECCHETTO GIADA', 'DI IULIO ISABELLA', 'RUMORI CHIARA'],
               'CUB':['MLINAR LUCIJA','KOOLHAAS NICOLE'],
               'CYP':'ORTOLANI SERENA',
               'CZE':['ANGELONI VERONICA','HAVELKOVA HELENA'],
               'ESP':'AELBRECHT FREYA',
               'EST':'BICI ERBLIRA',
               'FRA':'DEGRADI ALICE',
               'GER':['TURCO ALICE','GIOVANNINI GAIA'],
               'GRE':'CANDI SONIA',
               'ITA':['STRANTZALI OLGA', 'FAVA FRANCESCA', 'SIGNORILE NOEMI', 'STIJEPIC MILKA', 'ZANNONI GIORGIA', 'ZAKCHAIOU KATERINA', 'UNGUREANU ADELINA',
                      'GAY ALICE', 'PIANI VITTORIA', 'MARCONE BENEDETTA', 'TREVISAN FRANCESCA', 'MORO ILENIA', 'FONDRIEST SILVIA', 'CUMINO MARIA LUISA',
                      'RICCI MARIA IRENE', 'D ODORICO SOFIA', 'PIZZOLATO VALERIA', 'FURLAN ELEONORA', 'MELLI GIULIA', 'BISIO ELENA', 'POPULINI ALESSIA',
                      'HERBOTS BRITT', 'NAPODANO FRANCESCA', 'ZANETTE ELISA', 'BATTISTONI ILARIA', 'BOSETTI CATERINA', 'CHIRICHELLA CRISTINA', 'SANSONNA STEFANIA',
                      'HANCOCK MICHA DANIELLE', 'BONIFACIO SARA', 'WASHINGTON HALEIGH', 'SMARZEK MALWINA', 'DAALDEROP NIKA', 'ENWEONWU TERRY RUTH', 'VITTORINI ARIANNA',
                      'CAMBI CARLOTTA', 'LAZIC REBECKA', 'VAN GESTEL CELINE', 'ALBERTI SARA', 'PANETONI SARA', 'HASHIMOTO NAOKO', 'BELIEN YVON', 'GUERRA ANASTASIA',
                      'KONE FATIM YASSIMINA', 'NWAKALOR SYLVIA', 'ACCIARRI NAUSICA', 'VENTURI MAILA', 'CARAVELLO LARA', 'GICQUEL LUCILLE', 'BUTIGAN BOZANA',
                      'DE KRUIJF ROBIN', 'FOLIE RAPHAELA', 'OMORUYI LOVETH OGHOSASERE', 'DE GENNARO MONICA', 'ADAMS MCKENZIE ELISE', 'GENNARI GIULIA', 'WOLOSZ JOANNA',
                      'HILL KIMBERLY','SYLLA MIRIAM', 'EGONU PAOLA', 'FAHR SARAH', 'ALHASSAN RHAMAT', 'PERINELLI ELENA', 'BOSIO FRANCESCA', 'FRANTTI ALEXANDRA',
                      'MAYER VICTORIA', 'GIBERTINI GIULIA', 'GROBELNA KAJA', 'VILLANI FRANCESCA', 'DE BORTOLI CHIARA', 'LAAK KERTU', 'MAZZARO ALESSIA', 'ZAMBELLI MARINA',
                      'MEIJERS ANNICK', 'CARRARO GIULIA', 'SQUARCINI FEDERICA', 'HEYRMAN LAURA', 'VAN HECKE LISE', 'ORRO ALESSIA', 'BEGIC EDINA', 'DANESI ANNA', 'ORTHMANN HANNA',
                      'MEIJNERS FLOORTJE', 'OBOSSA JOSEPHINE', 'DAVYSKIBA HANNA', 'PARROCCHIALE BEATRICE', 'NEGRETTI BEATRICE', 'STYSIAK MAGDALENA', 'MALINOV OFELIA', 'POPOVIC MINA',
                      'MARKOVIC SRNA', 'PIETRINI ELENA', 'MERLO ENRICA', 'LUBIAN MARINA','CAROCCI LUNA VERONICA','CECCONELLO AGNESE','SAMADAN MARTINA','DREWNIOK KIMBERLY','BOSETTI LUCIA',
                      'COURTNEY MEGAN','CAMERA LETIZIA','POULTER JORDYN','OLIVOTTO ROSSELLA','GENNARI ALESSIA','BONELLI ASIA','GRAY ALEXA','LEONARDI GIULIA','MINGARDI CAMILLA',
                      'PICCININI FRANCESCA', 'CUCCO CHIARA'],
               'JPN':'STEVANOVIC JOVANA',
               'NED':['ESCAMILLA ANA','BULOVIC KATARINA','HERRERA BLANCO LISET','STUFI FEDERICA','LLOYD CARLI','PARTENIO LAURA','SIRRESSI IMMA'],
               'POL':['BONCIANI FRANCESCA','MONTIBELLER ROSAMARIA','MAGGIPINTO MARIANNA'],
               'PUR':['MELANDRI LAURA','VANZUROVA TEREZA'],
               'ROM':'CIARROCCHI MICHELA',
               'SRB':['MARINHO ANANDA CRISTINA','BAJEMA KARA','VASILEVA ELITSA','KOSAREVA DAYANA'],
               'SWE':'FAUCETTE JOHNSON JULIANN',
               'USA':['ENRIGHT STEPHANIE','PRANDI VITTORIA','FERSINO ELEONORA','MARCON FRANCESCA','LUKETIC KATARINA','DUMANCIC BETA','VALENTIN NATALIA', 'FARAONE GIORGIA',
                      'LANIER KHALIA','LODA SARA', 'MORETTO GAIA','MIO BERTOLO GIULIA']}

               #D'Orico Sofia l'ho scritto senza apostrofo perché non so come si faccia

input("Provide name and surname of the player ")
    
def player_nationality(NATIONALITY):
    for nationality,name in NATIONALITY.items():
        if name in NATIONALITY.values():
            return "Her nationality is " + nationality
        else:
            return "Her nationality is unknown"
        
print(player_nationality(NATIONALITY))



#choose_team
#get_members
